// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyi-tNx81EkUkNTJCrq79sXK5rrN0LACU',
    appId: '1:381062034167:web:49e5aa9be0920f8076d9f2',
    messagingSenderId: '381062034167',
    projectId: 'auth-57c4f',
    authDomain: 'auth-57c4f.firebaseapp.com',
    storageBucket: 'auth-57c4f.appspot.com',
    measurementId: 'G-GFS413BL0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-NtJq8XO4nBGDIqt4uGw1VqpSLjl3XO0',
    appId: '1:381062034167:android:d88423326689710976d9f2',
    messagingSenderId: '381062034167',
    projectId: 'auth-57c4f',
    storageBucket: 'auth-57c4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjMM9TwHfxWzYEOSkSVfWNzwAI27T-dVo',
    appId: '1:381062034167:ios:4efde832354d265976d9f2',
    messagingSenderId: '381062034167',
    projectId: 'auth-57c4f',
    storageBucket: 'auth-57c4f.appspot.com',
    iosClientId: '381062034167-84k030fhh68pq86s4ibthh6sglq2gjel.apps.googleusercontent.com',
    iosBundleId: 'com.example.audio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjMM9TwHfxWzYEOSkSVfWNzwAI27T-dVo',
    appId: '1:381062034167:ios:3d4c0b5ded4d3c4c76d9f2',
    messagingSenderId: '381062034167',
    projectId: 'auth-57c4f',
    storageBucket: 'auth-57c4f.appspot.com',
    iosClientId: '381062034167-48ke8ptu05t0v76323931ubejj94r4at.apps.googleusercontent.com',
    iosBundleId: 'com.example.audio.RunnerTests',
  );
}
